### ISSUE TITLE
Import accounts

### ISSUE THREAD

**Issue by hypixus** [Top-Cat/UnofficialSteamAuthenticator#63] opened 2016-04-13 07:36 UTC
Hello

is there any possibility to import accounts from SDA? I mean, we can export to .maFile-s (horray!) but we can't do this second way. Please, add this ability, or explain to people how to do this.

Thanks

hypixus

**Comment by Top-Cat** [comment] 2016-04-16 07:56
Duplicate of #18

**Closed by Top-Cat** 2016-04-16 07:56 UTC

**Comment by hypixus** [comment] 2016-05-07 19:23
@Top-Cat I meant import FROM sda, not to export :/

**Comment by Top-Cat** [comment] 2016-05-08 14:23
#18 very clearly says "Export / Import to SDA"
What's your problem?

**Comment by hypixus** [comment] 2016-05-09 07:03
I can't find it 😅

**Comment by Top-Cat** [comment] 2016-05-11 17:01
Can't find what? Just read my comment.

**Comment by hypixus** [comment] 2016-05-11 18:30
I did, few times, but please, provide me a step by step instruction :/

**Comment by Top-Cat** [comment] 2016-05-11 21:17
I don't know what you need help with
