### ISSUE TITLE
Confirm menu doesn't work.

### ISSUE THREAD

**Issue by Rogerinsky** [Top-Cat/UnofficialSteamAuthenticator#71] opened 2016-06-11 21:59 UTC
When I try to go to the confirmation screen to sell something in the market, it just doesn't load and returns me back to the code screen. I can't sell anything now.

**Comment by Top-Cat** [comment] 2016-06-11 23:55
Duplicate of #66 reply there if you can't fix it

**Closed by Top-Cat** 2016-06-11 23:55 UTC
