### ISSUE TITLE
Access to account's data

### ISSUE THREAD

**Issue by hypixus** [Top-Cat/UnofficialSteamAuthenticator#31] opened 2016-03-27 16:03 UTC
This is an enchancement - but really important, especially for people having parents like mine...

Could you please implement in near future ability for user to retrieve his SteamGuardAccount data? For example - to copy and paste somewhere? My parents love to take my phone so I haven't got an access to Steam without it. Recovering my account is not a way to go, so I am going to use https://github.com/Jessecar96/SteamDesktopAuthenticator for it. But, to generate codes or accept trades - .maFile is indeed. This file, as you propably expect, is just JSON interpretation of account, id and secret code , like this:

string sgFile = JsonConvert.SerializeObject(linker.LinkedAccount, Formatting.Indented); //linker = AuthenticatorLinker class
string fileName = linker.LinkedAccount.AccountName + ".maFile";
File.WriteAllText(fileName, sgFile);

In your app, whole thing is stored in settings.dat file, but - I was unable to extract it :/
Please, add ability to export them for user. I can even pay for that :P

**Comment by Top-Cat** [comment] 2016-03-27 16:09
Duplicate of #18

**Closed by Top-Cat** 2016-03-27 16:09 UTC

**Comment by setoy** [comment] 2016-03-27 17:16
You can print a list of Steam Guard Backup Codes here: https://store.steampowered.com/twofactor/manage

**Comment by hypixus** [comment] 2016-03-27 17:34
@setoy I meant backup of SteamGuardAccount instance, not backup code - I already made it ;)

**Comment by hypixus** [comment] 2016-03-27 17:36
@Top-Cat I don't know if it will work well, but I've added a commit with one line changed, please consider looking at it.(I don't exactly know how github commit, push or anything of this works, but - simply - I made a change using GIT COMMIT and wait for you to review it.)

**Comment by setoy** [comment] 2016-03-27 17:47
@hypixus I was just answering to your "parent-phone-issue". I mean, you surely know username and password. The only thing that requires you to use your phone is the authenticator code - which you can print in advance to combat this. :P

**Comment by hypixus** [comment] 2016-03-27 17:49
@setoy I've considered that already, but each recovery like that makes trade hold for 7 days - in my case, it's irresistable.
