### ISSUE TITLE
Trading Offers

### ISSUE THREAD

**Issue by jessejac** [Top-Cat/UnofficialSteamAuthenticator#77] opened 2016-06-28 16:21 UTC
Hey,
Im using ur App v.1.5.112
and im having a problem with my Trading offers.
If i click on the button for my tradeoffers the app shows ne a White screen vor 1 or 2 seconds and then returns to the guard screen.
Pls help me
Ty

**Comment by Top-Cat** [comment] 2016-06-28 16:34
Duplicate of #66 reply there if you can't fix it

**Closed by Top-Cat** 2016-06-28 16:34 UTC
